Technial documentation page
Hasinarahman/Technical-documentation-page pull request #1
Opened 2024-05-26 19:15 UTC by Hasinarahman

Creating a Technical documentation page.
- first create new repo for this page
- clone the repo in VS code
- create html file
- create css file
- in html file create a header for page 
- then create sidbar
- adding main section
- adding footer for page 
- design all these thing in css file 
- than push all changes to github.

2024-05-27 05:39 UTC, Hasinarahman commented
@ahzamir
hello sir I complete the documention page project.
please check it.

2024-05-27 06:45 UTC, ahzamir requested changes
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although you have done a great job by implementing all the requirements and your code passes all the checks on the freecodecmp website. But your HTML code is not clean check the inline comments for more details:

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
![image](https://github.com/Hasinarahman/Technical-documentation-page/assets/96838030/c3d3985d-0e80-4c20-a980-8ee202f63bc7)
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Technical Documentation Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌Your code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-27 06:45 UTC, ahzamir commented on index.html
Your HTML code is not clean and properly aligned. Please use 2 spaces for indentation instead of 4. Additionally, ensure that child elements are properly indented under their parent elements. Here's an example to help you:

**Incorrect:**
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
        <h1>This is a Heading</h1>
        <p>This is a paragraph.</p>
    </body>
</html>
```

**Correct:**
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <h1>This is a Heading</h1>
    <p>This is a paragraph.</p>
  </body>
</html>
```

**Rule:** Each child element should be indented 2 spaces under its parent element for better readability and maintainability.

2024-05-27 06:45 UTC, ahzamir commented on index.html
> +        <header>HTML and CSS</header>
- You should have only one `<header>` tag in your HTML file, instead you can have more `<h1>`, `<h2>`, `<h3>` ...
change your headers to `h` tags.

2024-05-28 06:13 UTC, Hasinarahman commented
**Hello sir @ahzamir** ,
I  clean the code of index.html file.
You say we should have  one <header> tag in our HTML file, 
at first time I do this instead of header I added **h1,h2,**h3**  tags** in my cod when I paste in freecodecaomp it **does not work and give me error**  because it says like this (The first element within each .main-section should be a header element, which contains text that describes the topic of that section ) and when added a header in each section it accept the code for that I add header in each section instead of h1 tag.

I hope my project will be approved this time.

2024-05-28 23:43 UTC, ahzamir commented
@Hasinarahman 

- Well done you implemented the feedback very well but your project still, misses the requirement below.
- Your project README.md file is not professional and does not contain the project details.

2024-05-30 08:41 UTC, Hasinarahman commented
hello teacher @ahzamir ,
I  was adding details in readme file so I will still for your feedback.
also thanks for helping.

2024-06-01 08:03 UTC, ahzamir requested changes
@Hasinarahman 

- Well done you added a README.mdto your project but still your README.md file is not professional
  - Check the inline comments below for more details

2024-06-01 08:03 UTC, ahzamir commented on README.md
> +
- Remove this part

2024-06-01 08:03 UTC, ahzamir commented on README.md
> +- git cd "name of your folder"
- You have to copy and past your project ssh key in the "your ssh key" section
- And also your repo name 

And make it like a code example just by adding this:
  - Remove the parenthesis `(  )` and add your project ssh key link in the required section and also your project folder name:
```
(```
# git clone SSH KEY LINK OF YOUR OWN PROJECT HERE
```)
(```
# cd YOUR REPO NAME
```)
```

2024-06-02 14:03 UTC, Hasinarahman commented
Hello sir @ahzamir ,
I update the readme file please give me feedback.
and thanks for your helping .

2024-06-04 18:12 UTC, Hasinarahman commented
Hello sir @ahzamir ,
until now I am waiting for your feedback.

2024-06-05 19:55 UTC, ahzamir commented
@Hasinarahman 

- Ask your partner to review your README.md file and provide you feedback.

2024-06-06 04:13 UTC, Hasinarahman commented
> Hello sir @ahzamir , I update the readme file please give me feedback. and thanks for your helping .

![t- page](https://github.com/Hasinarahman/Technical-documentation-page/assets/168626170/86f65f16-32c9-453c-b975-f5f5aa70f7c6)

2024-06-06 04:13 UTC, closed without merging